<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Version>8.2.0</Version>
    <Authors>Supershift B.V.</Authors>
    <Company>Supershift B.V.</Company>
    <Description>Provides UI classes to use Sushi.Mailtemplate in Sushi.MediaKiwi.</Description>
	<Copyright>2019-2025 Supershift B.V.</Copyright>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Supershift/Sushi.MailTemplate</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Supershift/Sushi.MailTemplate</RepositoryUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sushi.MailTemplate\Sushi.MailTemplate.csproj" />
    <ProjectReference Include="..\Sushi.Mediakiwi\Sushi.Mediakiwi.csproj" />
  </ItemGroup>

</Project>
