//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi.Mediakiwi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Markup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Markup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sushi.Mediakiwi.Markup", typeof(Markup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Reset your password&lt;/h1&gt;
        ///&lt;p&gt;
        ///    Your password needs to be (re)applied.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Apply a minimum of 8 characters in length which should contain one of every character type: Uppercase, lowercase, number &amp; symbol.
        ///&lt;/p&gt;
        ///&lt;table&gt;
        ///    &lt;tr&gt;
        ///        &lt;td colspan=&quot;2&quot;&gt;
        ///            &lt;input type=&quot;text&quot; name=&quot;username&quot; placeholder=&quot;Email&quot; disabled=&quot;disabled&quot; class=&quot;long&quot; id=&quot;username&quot; value=&quot;[[MK_INPUT_USER]]&quot; /&gt;
        ///        &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///        &lt;td colspan=&quot;2&quot;&gt;&lt;input type=&quot;password&quot; class=&quot;[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string component_applypassword {
            get {
                return ResourceManager.GetString("component_applypassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[MK_SIGNIN_AREA]]
        ///&lt;h1&gt;Sign in with your email&lt;/h1&gt;
        ///&lt;table&gt;
        ///    &lt;tfoot&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;&lt;a href=&quot;[[MK_LOST_PWD]]&quot;&gt;Lost password?&lt;/a&gt;&lt;/td&gt;
        ///            &lt;td&gt;
        ///                &lt;button id=&quot;submitBTN&quot; class=&quot;action&quot; value=&quot;Login&quot;&gt;Login&lt;/button&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/tfoot&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td colspan=&quot;2&quot;&gt;
        ///                &lt;input type=&quot;text&quot; name=&quot;username&quot; placeholder=&quot;Email&quot; id=&quot;username&quot; class=&quot;long[[MK_INPUT_ERR]]&quot; value=&quot;[[MK_INPUT_USER]]&quot; /&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string component_login {
            get {
                return ResourceManager.GetString("component_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Reset my password&lt;/h1&gt;
        ///&lt;p&gt;Please enter your email adress below and we&apos;ll send you instructions on how to reset your password.&lt;/p&gt;
        ///&lt;table&gt;
        ///    &lt;tfoot&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;&lt;a href=&quot;[[MK_LOGIN]]&quot;&gt;Return to the login&lt;/a&gt;&lt;/td&gt;
        ///            &lt;td&gt;
        ///                &lt;button id=&quot;submitBTN&quot; class=&quot;action&quot;&gt;Next&lt;/button&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/tfoot&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td colspan=&quot;2&quot;&gt;
        ///                &lt;input type=&quot;email&quot; name=&quot;email&quot; placeholder=&quot;Email&quot; id=&quot;email&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string component_reminder {
            get {
                return ResourceManager.GetString("component_reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///    &lt;title&gt;[[MK_ENV_TITLE]]&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=Edge&quot; /&gt;
        ///    &lt;meta name=&quot;robots&quot; content=&quot;noindex&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;[[MK_CDN_PATH]]compiled/bundel_login.min.css&quot; type=&quot;text/css&quot; media=&quot;all&quot; /&gt;
        ///    [[MK_STYLE]]
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;[[MK_CDN_PATH]]compiled/bundel_login.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;!--[if IE]&gt;
        ///        &lt;meta http-equiv=&quot;imagetoolbar&quot; content=&quot;no&quot;/&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	CREATE TABLE wim_Installers(
        ///	    Installer_Key int IDENTITY(1,1) NOT NULL,
        ///	    Installer_GUID uniqueidentifier NOT NULL,
        ///	    Installer_Folder_Key int NULL,
        ///	    Installer_Name nvarchar(50) NOT NULL,
        ///	    Installer_Assembly varchar(150) NULL,
        ///	    Installer_ClassName varchar(250) NULL,
        ///	    Installer_Description nvarchar(1024) NULL,
        ///	    Installer_Settings xml NULL,
        ///	    Installer_Version int NOT NULL,
        ///	    Installer_Installed datetime NULL);
        ///	
        ///	--PK_Installer_Key;
        ///	IF:select COUNT(*) from s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wim_base {
            get {
                return ResourceManager.GetString("wim_base", resourceCulture);
            }
        }
    }
}
