//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi.Mediakiwi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sushi.Mediakiwi.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from page.
        /// </summary>
        internal static string _CopyFromPage {
            get {
                return ResourceManager.GetString("_CopyFromPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string _description {
            get {
                return ResourceManager.GetString("_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filesize.
        /// </summary>
        internal static string _filesize {
            get {
                return ResourceManager.GetString("_filesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string _folder {
            get {
                return ResourceManager.GetString("_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string _Info {
            get {
                return ResourceManager.GetString("_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is default.
        /// </summary>
        internal static string _is_default {
            get {
                return ResourceManager.GetString("_is_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is searchable.
        /// </summary>
        internal static string _is_searchable {
            get {
                return ResourceManager.GetString("_is_searchable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is secure.
        /// </summary>
        internal static string _is_secure {
            get {
                return ResourceManager.GetString("_is_secure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linktext.
        /// </summary>
        internal static string _linktext {
            get {
                return ResourceManager.GetString("_linktext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string _name {
            get {
                return ResourceManager.GetString("_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string _save {
            get {
                return ResourceManager.GetString("_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for.
        /// </summary>
        internal static string _search_for {
            get {
                return ResourceManager.GetString("_search_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        internal static string _selectfile {
            get {
                return ResourceManager.GetString("_selectfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolder.
        /// </summary>
        internal static string _subfolder {
            get {
                return ResourceManager.GetString("_subfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string _title {
            get {
                return ResourceManager.GetString("_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string channel {
            get {
                return ResourceManager.GetString("channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy content .
        /// </summary>
        internal static string copy_page_content {
            get {
                return ResourceManager.GetString("copy_page_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source page &apos;#sourcePageName#&apos; has #sourceComponentLength# components and last changed #sourceChanged#&lt;br/&gt;Target page &apos;#targetPageName#&apos; has #targetComponentLength# components and last changed #targetChanged#.
        /// </summary>
        internal static string CopyContentInfo {
            get {
                return ResourceManager.GetString("CopyContentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom actions.
        /// </summary>
        internal static string custom_actions {
            get {
                return ResourceManager.GetString("custom_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM-dd-yyyy HH:mm.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to perform this action?.
        /// </summary>
        internal static string delete_confirm {
            get {
                return ResourceManager.GetString("delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string delete_confirm_title {
            get {
                return ResourceManager.GetString("delete_confirm_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail view.
        /// </summary>
        internal static string detail_view {
            get {
                return ResourceManager.GetString("detail_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file.
        /// </summary>
        internal static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong when trying to access the requested item..
        /// </summary>
        internal static string err_0 {
            get {
                return ResourceManager.GetString("err_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested list does not exist or you don&apos;t have the proper rights to view this list..
        /// </summary>
        internal static string err_1001 {
            get {
                return ResourceManager.GetString("err_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the required access rights to access this system..
        /// </summary>
        internal static string err_1002 {
            get {
                return ResourceManager.GetString("err_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the required access rights to access this data..
        /// </summary>
        internal static string err_1003 {
            get {
                return ResourceManager.GetString("err_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a page to copy from.
        /// </summary>
        internal static string Errror_SelectPage {
            get {
                return ResourceManager.GetString("Errror_SelectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data.
        /// </summary>
        internal static string export_data {
            get {
                return ResourceManager.GetString("export_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to PDF.
        /// </summary>
        internal static string export_pdf {
            get {
                return ResourceManager.GetString("export_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string export_xls {
            get {
                return ResourceManager.GetString("export_xls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        internal static string folder_new {
            get {
                return ResourceManager.GetString("folder_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder options.
        /// </summary>
        internal static string folder_options {
            get {
                return ResourceManager.GetString("folder_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder properties.
        /// </summary>
        internal static string folder_properties {
            get {
                return ResourceManager.GetString("folder_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no visible search columns selected..
        /// </summary>
        internal static string grid_no_search_columns {
            get {
                return ResourceManager.GetString("grid_no_search_columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records.
        /// </summary>
        internal static string grid_records {
            get {
                return ResourceManager.GetString("grid_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string grid_total {
            get {
                return ResourceManager.GetString("grid_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string input_code {
            get {
                return ResourceManager.GetString("input_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string input_doc {
            get {
                return ResourceManager.GetString("input_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string input_image {
            get {
                return ResourceManager.GetString("input_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string input_link {
            get {
                return ResourceManager.GetString("input_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string input_richtext {
            get {
                return ResourceManager.GetString("input_richtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        internal static string list_browsing {
            get {
                return ResourceManager.GetString("list_browsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New list.
        /// </summary>
        internal static string list_new {
            get {
                return ResourceManager.GetString("list_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as.
        /// </summary>
        internal static string logged_in_as {
            get {
                return ResourceManager.GetString("logged_in_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New asset.
        /// </summary>
        internal static string new_asset {
            get {
                return ResourceManager.GetString("new_asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New item.
        /// </summary>
        internal static string new_record {
            get {
                return ResourceManager.GetString("new_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the text to which the link will apply..
        /// </summary>
        internal static string no_link_selected {
            get {
                return ResourceManager.GetString("no_link_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page content.
        /// </summary>
        internal static string page_content {
            get {
                return ResourceManager.GetString("page_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page history.
        /// </summary>
        internal static string page_history {
            get {
                return ResourceManager.GetString("page_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit.
        /// </summary>
        internal static string page_inherit {
            get {
                return ResourceManager.GetString("page_inherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View live.
        /// </summary>
        internal static string page_live {
            get {
                return ResourceManager.GetString("page_live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localise.
        /// </summary>
        internal static string page_localise {
            get {
                return ResourceManager.GetString("page_localise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New page.
        /// </summary>
        internal static string page_new {
            get {
                return ResourceManager.GetString("page_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal mode.
        /// </summary>
        internal static string page_normalmode {
            get {
                return ResourceManager.GetString("page_normalmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page options.
        /// </summary>
        internal static string page_options {
            get {
                return ResourceManager.GetString("page_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy master.
        /// </summary>
        internal static string page_pastemode {
            get {
                return ResourceManager.GetString("page_pastemode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string page_preview {
            get {
                return ResourceManager.GetString("page_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page properties.
        /// </summary>
        internal static string page_properties {
            get {
                return ResourceManager.GetString("page_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string page_publish {
            get {
                return ResourceManager.GetString("page_publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Offline.
        /// </summary>
        internal static string page_takeoffline {
            get {
                return ResourceManager.GetString("page_takeoffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation mode.
        /// </summary>
        internal static string page_translationmode {
            get {
                return ResourceManager.GetString("page_translationmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal.
        /// </summary>
        internal static string portal {
            get {
                return ResourceManager.GetString("portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string properties {
            get {
                return ResourceManager.GetString("properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please apply all required fields..
        /// </summary>
        internal static string required_fields {
            get {
                return ResourceManager.GetString("required_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback.
        /// </summary>
        internal static string Rollback {
            get {
                return ResourceManager.GetString("Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and new.
        /// </summary>
        internal static string save_and_new {
            get {
                return ResourceManager.GetString("save_and_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show result.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string section_admin {
            get {
                return ResourceManager.GetString("section_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images and documents.
        /// </summary>
        internal static string section_galleries {
            get {
                return ResourceManager.GetString("section_galleries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data lists.
        /// </summary>
        internal static string section_logic {
            get {
                return ResourceManager.GetString("section_logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string section_web {
            get {
                return ResourceManager.GetString("section_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string subscribe_to_list {
            get {
                return ResourceManager.GetString("subscribe_to_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main content column.
        /// </summary>
        internal static string tab_Content {
            get {
                return ResourceManager.GetString("tab_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right content column.
        /// </summary>
        internal static string tab_ServiceColumn {
            get {
                return ResourceManager.GetString("tab_ServiceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail view.
        /// </summary>
        internal static string thumbnail_view {
            get {
                return ResourceManager.GetString("thumbnail_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn sort order off.
        /// </summary>
        internal static string turn_sort_order_off {
            get {
                return ResourceManager.GetString("turn_sort_order_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn sort order on.
        /// </summary>
        internal static string turn_sort_order_on {
            get {
                return ResourceManager.GetString("turn_sort_order_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
